# Generated by Django 4.2.1 on 2023-05-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.team'),
        ),
    ]
